name: Run Tests

on:
  push:
    branches: [main, master] # runs on pushes to main/master
  pull_request:
    branches: [main, master] # runs on PRs targeting main/master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # or whatever version you're using
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
